name: patreon
description: Code for demoing purposes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^3.2.0
  firebase_core: ^1.10.5 
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true