name: patreon
description: Code for demoing purposes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.1.1 
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.7.0
  firebase_core: ^1.10.5 
  firebase_messaging: ^11.1.0
  freezed_annotation:
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.5
  freezed: ^0.15.1+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true