name: patreon
description: Code for demoing purposes.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.4.6
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.5 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true