name: instagram_clone_flutter
description: A new Flutter project.

publish_to: 'none' 
 
version: 1.0.2+2

environment:
  sdk: ">=2.15.0 <3.0.0"
 
dependencies:
  cloud_firestore: ^4.8.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  firebase_messaging: ^14.7.9
  flutter_fcm_wrapper: ^0.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^2.0.7
  image_picker: ^0.8.4+4
  intl: ^0.18.1
  provider: ^6.0.1
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/ic_instagram.svg 